repos:
-   repo: https://github.com/ambv/black
    rev: 25.1.0
    hooks:
    - id: black

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort

-   repo: https://github.com/pycqa/pylint
    rev: v3.3.6
    hooks:
    -   id: pylint

-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.397
    hooks:
    - id: pyright

-   repo: https://github.com/repo-helper/pyproject-parser
    rev: v0.13.0 
    hooks:
    - id: check-pyproject
    - id: reformat-pyproject

-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.9
    hooks:
      - id: uv-lock
